import { Building2, Database, Save, Shield, Tags } from "lucide-react";
function SettingsPage(){
 return <div className="min-h-screen bg-[#F3F5F7] text-[#243746]"><header className="border-b border-slate-200 bg-white"><div className="flex min-h-20 items-center px-5 md:px-8"><div><h1 className="text-xl font-bold md:text-2xl">Settings</h1><p className="text-sm text-slate-500">System configuration and record defaults</p></div></div></header>
 <main className="max-w-5xl p-5 md:p-8"><div className="space-y-5">
  <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex gap-3 border-b border-slate-200 p-5"><Building2 className="text-[#08689F]" size={21}/><div><h2 className="font-bold">Office Information</h2><p className="text-sm text-slate-500">Identity shown throughout the internal system.</p></div></div><div className="grid gap-5 p-6 md:grid-cols-2"><label className="text-sm font-semibold">Office Name<input defaultValue="GSIS Dumaguete Branch Office" className="mt-2 h-12 w-full rounded-md border border-slate-300 px-3 font-normal"/></label><label className="text-sm font-semibold">Default Records Location<input defaultValue="Records Section" className="mt-2 h-12 w-full rounded-md border border-slate-300 px-3 font-normal"/></label></div></section>
  <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex gap-3 border-b border-slate-200 p-5"><Tags className="text-[#08689F]" size={21}/><div><h2 className="font-bold">Record Categories</h2><p className="text-sm text-slate-500">Categories currently used by the prototype.</p></div></div><div className="grid gap-3 p-6 sm:grid-cols-2">{["Policy Envelope","Active File","Inactive File","Retirement"].map(x=><div key={x} className="rounded-md border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold">{x}</div>)}</div></section>
  <section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><Database className="text-[#08689F]" size={21}/><div><h2 className="font-bold">Database & Security</h2><p className="mt-1 text-sm leading-relaxed text-slate-500">Backend connection, backups, password policies, audit retention, and database configuration will be available after the Spring Boot and PostgreSQL services are connected.</p><div className="mt-4 flex items-center gap-2 text-xs font-semibold text-slate-400"><Shield size={16}/>Backend not connected</div></div></div></section>
  <div className="flex justify-end"><button onClick={()=>alert("Prototype only: settings persistence will be enabled with the backend.")} className="flex items-center gap-2 rounded-md bg-[#08689F] px-5 py-2.5 text-sm font-semibold text-white"><Save size={17}/>Save Settings</button></div>
 </div></main></div>;
}
export default SettingsPage;
